### ISSUE TITLE
Parser for XNVME_CLI_OPT_VTYPE_NUM parses hex value as 0

### ISSUE THREAD

**Issue by Baekalfen** [OpenMPDK/xNVMe#546] opened 2024-10-25 11:01 UTC
The parser tries to convert the string `0x4096` as a base-10 integer, and returns `0`. The order of the arguments are insignificant, and it will throw away the `x4096` part. The expected behavior would be to either parse the hex value correctly, or return an error.

```
./builddir/tools/lblk write [URI] ... --slba 0x0 --nlb 0x4096
# Writing nsid: 0x1, slba: 0x0000000000000000, nlb: 0
# Alloc/fill dbuf, dbuf_nbytes: 512
# Sending the command...
```

```
./builddir/tools/lblk write [URI] ... --slba 0x0 --nlb 4096
# Writing nsid: 0x1, slba: 0x0000000000000000, nlb: 4096
# Alloc/fill dbuf, dbuf_nbytes: 2097664
# Sending the command...
```

**Comment by safl** [comment] 2024-10-25 11:20
This is intended behavior, see usage of ``lblk`` below, ``nlb`` has has: ``--nlb NUM``  not ``--nlb 0xNUM``.

```
Usage: lblk write <uri> [<args>]

Writes data and optionally metadata

Positional arguments:

  uri                           ; Device URI e.g. '/dev/nvme0n1', '0000:01:00.1', '10.9.8.1.8888', '\\.\PhysicalDrive1'

Where <args> include:

  --slba 0xNUM                  ; Start Logical Block Address
  --nlb NUM                     ; Number of LBAs (NOTE: zero-based value)
  [ --nsid 0xNUM ]              ; Namespace Identifier for Command Construction
  [ --data-input FILE ]         ; Path to data input-file
  [ --meta-input FILE ]         ; Path to meta input-file

With <args> for backend:

  [ --subnqn STRING ]           ; Subsystem NQN of the NVMe over Fabrics endpoint e.g. 'nqn.2022-06.io.xnvme:ctrlnode1'
  [ --hostnqn STRING ]          ; The host NQN to use when connecting to NVMe over Fabrics controllers
  [ --be STRING ]               ; xNVMe backend, e.g. 'linux', 'spdk', 'fbsd', 'macos', 'posix', 'windows'
  [ --dev-nsid 0xNUM ]          ; Namespace Identifier for Device Handle
  [ --admin STRING ]            ; xNVMe admin. command-interface, e.g. 'nvme', 'block'
  [ --mem STRING ]              ; xNVMe buffer/memory manager
  [ --direct NUM ]              ; Bypass layers
  [ --sync STRING ]             ; xNVMe sync. command-interface, e.g. 'nvme', 'block'
  [ --help ]                    ; Show usage / help
```

**Comment by Baekalfen** [comment] 2024-10-25 15:15
I can see it's supposed to parse a hexadecimal and decimal number, but surely it's not intended to silently ignore these?

```
lblk write 2GB --dev-nsid 1 --be ramdisk --admin ramdisk --slba 0x1HHHHHHHHHH --nlb 0KKKKKKK
# Writing nsid: 0x1, slba: 0x0000000000000001, nlb: 0
# Alloc/fill dbuf, dbuf_nbytes: 512
# Sending the command...
```

```
lblk write 2GB --dev-nsid 1 --be ramdisk --admin ramdisk --slba 0x1HHHHHHHHHH --nlb 0KKKKKKK
# Writing nsid: 0x1, slba: 0x0000000000000001, nlb: 0
# Alloc/fill dbuf, dbuf_nbytes: 512
# Sending the command...
```

```
lblk write 2GB --dev-nsid 1 --be ramdisk --admin ramdisk --slba 0x1HHHHHHHHHH --nlb 0--async=NOT_A_BACKEND
# Writing nsid: 0x1, slba: 0x0000000000000001, nlb: 0
# Alloc/fill dbuf, dbuf_nbytes: 512
# Sending the command...
```

**Comment by karlowich** [comment] 2024-10-28 09:48
@Baekalfen This is the default behaviour of [`strtoll`](https://linux.die.net/man/3/strtoll).
In `xnvme_cli.c` we have:
```
		case XNVME_CLI_OPT_VTYPE_NUM:
		case XNVME_CLI_OPT_VTYPE_HEX:
			errno = 0;
			num = strtoll(arg, &endptr, num_base);
			if (errno) {
				XNVME_DEBUG("FAILED: strtoll(), errno: %d", errno);
				errno = EINVAL;
				return -1;
			}
			if (arg == endptr) {
				XNVME_DEBUG("FAILED: strtoll(), no num. !");
				errno = EINVAL;
				return -1;
			}
			break;
```
To enable the behaviour you describe we should check the `endptr`
> In particular, if *nptr is not '\0' but **endptr is '\0' on return, the entire string is valid.

**Comment by safl** [comment] 2024-10-28 18:46
@Baekalfen To clarify, the parser is not "wrong". However, I agree that having input validation with descriptive error messages would be helpful. For instance, it could have saved a lot of confusion in this CLI usage. It would be great to add this feature.

**Comment by karlowich** [comment] 2024-11-11 13:07
Closing this since #547 has been merged

**Closed as completed by karlowich** 2024-11-11 13:07 UTC
Labels: enhancement
